import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import RootLayout, { metadata } from "./layout";

describe("RootLayout", () => {
  it("renders children content (SSR)", () => {
    const html = renderToStaticMarkup(
      <RootLayout>
        <div data-testid="child">Hello world</div>
      </RootLayout>
    );
    expect(html).toContain("Hello world");
  });
});

describe("metadata", () => {
  it("contains the expected title and description", () => {
    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });
});